Dieta   Menu de dieta     Debe existir un ttulo     Debe existir un porcentaje de ingesta diaria     Debe mostrar un conjunto de platos     Debe mostrar kcal     Debe mostrar proteinas     Debe mostrar grasas     Debe mostrar hidratos de carbono     Debe mostrar un plato (FAILED - 1)
Failures:

  1) Dieta Menu de dieta Debe mostrar un plato
     Failure/Error: expect(@menu.get_plato(1)).to eq(['Pera','1 unidad','60gr'])

     NoMethodError:
       undefined method `get_plato' for #<Dieta::Dieta:0x0000000156c448>
     # ./spec/Dieta_spec.rb:41:in `block (3 levels) in <top (required)>'

Finished in 0.00207 seconds (files took 0.06596 seconds to load)
8 examples, 1 failure

Failed examples:

rspec ./spec/Dieta_spec.rb:40 # Dieta Menu de dieta Debe mostrar un plato
Prueba para obtener un plato