Extraer el primer elemento de la lista (FAILED - 1)
Failures:

  1) Lista Pruebas de la lista Extraer el primer elemento de la lista
     Failure/Error: expect(@lista1.extract()).to eq(7)

     NoMethodError:
       undefined method `extract' for #<Lista:0x00000000c07e48 @head=nil>
     # ./spec/Dieta_spec.rb:82:in `block (3 levels) in <top (required)>'

Finished in 0.00587 seconds (files took 0.08359 seconds to load)
13 examples, 1 failure

Failed examples:

rspec ./spec/Dieta_spec.rb:81 # Lista Pruebas de la lista Extraer el primer elemento de la lista
Prueba pata la implementacion de extract