Pruebas nodo   Debe existir un nodo     Debe existir un nodo con su siguiente, su anterior y su dato
Lista_DE
  Pruebas de la lista_DE
    Insertar por el inicio un elemento a la lista
    Insertar varios por el inicio elementos en la lista_DE
    Extraer el primer elemento de la lista
    Debe existir un tail
    Insertar por el final un elemento en la lista
    Extraer por el final un elemento de la lista

Dieta
  Pruebas de herencia
    Dieta es superclass de Edad
    Mostrar el contenido
    Dieta es superclass de alimentos
    Mostrar el contenido alimentos (FAILED - 1)

Failures:

  1) Dieta Pruebas de herencia Mostrar el contenido alimentos
     Failure/Error: expect(@alimentos.mostrar_alimentos).to eq("MERIENDA (15%)\n- Manzana, 1 unidad, 60gr\n- Pera, 1 unidad, 60gr\nV.C.T | %\t400 kcal | 10% - 20% - 10%\nverduras y hortalizas")

     NoMethodError:
       undefined method `mostrar_alimentos' for #<Dieta::Edad:0x00000002719448>
       Did you mean?  mostrar_edad
     # ./spec/Menu_spec.rb:151:in `block (3 levels) in <top (required)>'

Finished in 0.00291 seconds (files took 0.07092 seconds to load)
11 examples, 1 failure

Failed examples:

rspec ./spec/Menu_spec.rb:150 # Dieta Pruebas de herencia Mostrar el contenido alimentos
Creando el mostrar