Pruebas nodo   Debe existir un nodo     Debe existir un nodo con su siguiente, su anterior y su dato
Lista_DE
  Insertar un elemento a la lista (FAILED - 1)

Failures:

  1) Lista_DE Insertar un elemento a la lista
     Failure/Error: @lista_DE1.insert_ini(5)

     NoMethodError:
       undefined method `insert_ini' for nil:NilClass
     # ./spec/Menu_spec.rb:86:in `block (2 levels) in <top (required)>'

Finished in 0.00185 seconds (files took 0.08317 seconds to load)
2 examples, 1 failure

Failed examples:

rspec ./spec/Menu_spec.rb:84 # Lista_DE Insertar un elemento a la lista

Pruebas para insert