Lista   Pruebas de la lista     Insertar un elemento a la lista (FAILED - 1)
Failures:

  1) Lista Pruebas de la lista Insertar un elemento a la lista
     Failure/Error: @lista1.insert(5)

     NoMethodError:
       undefined method `insert' for #<Lista:0x000000010d7bd0>
       Did you mean?  inspect
     # ./spec/Dieta_spec.rb:70:in `block (3 levels) in <top (required)>'

Finished in 0.00313 seconds (files took 0.07081 seconds to load)
11 examples, 1 failure

Failed examples:

rspec ./spec/Dieta_spec.rb:69 # Lista Pruebas de la lista Insertar un elemento a la list
Prueba oara sinsertar un elelemnto en la lista