Pruebas nodo   Debe existir un nodo     Debe existir un nodo con su siguiente, su anterior y su dato
Lista_DE
  Pruebas de la lista_DE
    Insertar por el inicio un elemento a la lista
    Insertar varios por el inicio elementos en la lista_DE
    Extraer el primer elemento de la lista
    Debe existir un tail
    Insertar por el final un elemento en la lista
    Extraer por el final un elemento de la lista (FAILED - 1)

Failures:

  1) Lista_DE Pruebas de la lista_DE Extraer por el final un elemento de la lista
     Failure/Error: expect(@lista_DE1.extract_fin()).to eq(4)

     NoMethodError:
       undefined method `extract_fin' for #<Lista_DE:0x00000001f52ef8>
       Did you mean?  extract_ini
     # ./spec/Menu_spec.rb:117:in `block (3 levels) in <top (required)>'

Finished in 0.00383 seconds (files took 0.09275 seconds to load)
7 examples, 1 failure

Failed examples:

rspec ./spec/Menu_spec.rb:115 # Lista_DE Pruebas de la lista_DE Extraer por el final un elemento de la lista

Pruebas para crear el extract