Pruebas nodo   Debe existir un nodo     Debe existir un nodo con su siguiente, su anterior y su dato
Lista_DE
  Pruebas de la lista_DE
    Insertar por el inicio un elemento a la lista
    Insertar varios por el inicio elementos en la lista_DE
    Extraer el primer elemento de la lista
    Debe existir un tail
    Insertar por el final un elemento en la lista
    Extraer por el final un elemento de la lista

Dieta
  Pruebas de herencia
    Dieta es superclass de Edad
    Mostrar el contenido (FAILED - 1)

Failures:

  1) Dieta Pruebas de herencia Mostrar el contenido
     Failure/Error: expect(@edad1.mostrar_edad).to eq("1) MERIENDA (15%)\n- Manzana, 1 unidad, 60gr\n4 a 8 años")

     NoMethodError:
       undefined method `mostrar_edad' for #<Dieta::Edad:0x000000016fc740>
     # ./spec/Menu_spec.rb:141:in `block (3 levels) in <top (required)>'

Finished in 0.00282 seconds (files took 0.07315 seconds to load)
9 examples, 1 failure

Failed examples:

rspec ./spec/Menu_spec.rb:140 # Dieta Pruebas de herencia Mostrar el contenido
Pruebas para mostrar