Dieta   Menu de dieta     Debe existir un ttulo (FAILED - 1)
Failures:

  1) Dieta Menu de dieta Debe existir un ttulo
     Failure/Error: menu=Dieta.new(['DESAYUNO'])

     NoMethodError:
       undefined method `new' for Dieta:Module
     # ./spec/Dieta_spec.rb:9:in `block (3 levels) in <top (required)>'

Finished in 0.00076 seconds (files took 0.06556 seconds to load)
1 example, 1 failure

Failed examples:

rspec ./spec/Dieta_spec.rb:12 # Dieta Menu de dieta Debe existir un ttulo
Creando prueba para titulo