Pruebas nodo   Debe existir un nodo     Debe existir un nodo con su siguiente, su anterior y su dato
Lista_DE
  Pruebas de la lista_DE
    Insertar por el inicio un elemento a la lista
    Insertar varios por el inicio elementos en la lista_DE
    Extraer el primer elemento de la lista (FAILED - 1)

Failures:

  1) Lista_DE Pruebas de la lista_DE Extraer el primer elemento de la lista
     Failure/Error: expect(@lista_DE1.extract_ini()).to eq(7)

     NoMethodError:
       undefined method `extract_ini' for #<Lista_DE:0x0000000253dcc8>
       Did you mean?  extract
     # ./spec/Menu_spec.rb:100:in `block (3 levels) in <top (required)>'

Finished in 0.00185 seconds (files took 0.06797 seconds to load)
4 examples, 1 failure

Failed examples:

rspec ./spec/Menu_spec.rb:98 # Lista_DE Pruebas de la lista_DE Extraer el primer elemento de la lista
Pruebas para extract_init