Pruebas nodo   Debe existir un nodo     Debe existir un nodo con su siguiente, su anterior y su dato
Lista_DE
  Pruebas de la lista_DE
    Insertar por el inicio un elemento a la lista
    Insertar varios por el inicio elementos en la lista_DE
    Extraer el primer elemento de la lista
    Debe existir un tail
    Insertar por el final un elemento en la lista
    Extraer por el final un elemento de la lista
  Pruebas de la lista_DE probando menus
    Introduciendo menus
    Mostrar el contenido
  Pruebas Enumerable Numeros
    Insertando valores
    Se puede hacer MAX (FAILED - 1)

Dieta
  Pruebas de herencia
    Dieta es superclass de Edad
    Mostrar el contenido
    Dieta es superclass de alimentos
    Pruebas de herencia
    Mostrar el contenido alimentos

Failures:

  1) Lista_DE Pruebas Enumerable Numeros  Se puede hacer MAX
     Failure/Error: expect(@listaE.max).to eq(3)

     NoMethodError:
       undefined method `max' for #<Lista_DE:0x00000002993a98>
     # ./spec/Menu_spec.rb:140:in `block (3 levels) in <top (required)>'

Finished in 0.00563 seconds (files took 0.07696 seconds to load)
16 examples, 1 failure

Failed examples:

rspec ./spec/Menu_spec.rb:138 # Lista_DE Pruebas Enumerable Numeros  Se puede hacer MAX
Prueba para implementar enumerable (each)