Pruebas nodo   Debe existir un nodo     Debe existir un nodo con su siguiente, su anterior y su dato
Lista_DE
  Pruebas de la lista_DE
    Insertar por el inicio un elemento a la lista
    Insertar varios por el inicio elementos en la lista_DE
    Extraer el primer elemento de la lista
    Debe existir un tail (FAILED - 1)

Failures:

  1) Lista_DE Pruebas de la lista_DE Debe existir un tail
     Failure/Error: expect(@lista_DE1.tail[:v]).to eq(5)

     NoMethodError:
       undefined method `tail' for #<Lista_DE:0x00000001f74710>
       Did you mean?  taint
     # ./spec/Menu_spec.rb:106:in `block (3 levels) in <top (required)>'

Finished in 0.00199 seconds (files took 0.06913 seconds to load)
5 examples, 1 failure

Failed examples:

rspec ./spec/Menu_spec.rb:104 # Lista_DE Pruebas de la lista_DE Debe existir un tail

Pruebas para implementar el tailwq